unique_ids:
  forms:
    Form1: X5JMXIE5PYOC5IFRGUECBRNEVMP7S6VY
    colorpicker: '1645166691595210600124028.85132'
    colorpicker_alternative_solution: KATD5WQD3V5BO62GS7VPUMCNKRT72MEW
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: EHERMLG566DZWAWKR253QUIEQ7TDD5XD
    theme.css: UZTMKNIPJMU2AMIXYXYFORERUVTAUS6H
